"""add is_active to users and delivery_employee_id to orders

Revision ID: e823f75c23e7
Revises: 31ef960bbdfd
Create Date: 2026-08-17 16:17:47.621085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e823f75c23e7'
down_revision: Union[str, Sequence[str], None] = '31ef960bbdfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_employee_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['delivery_employee_id'], ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_employee_id')
    # ### end Alembic commands ###
